#!/usr/bin/env bun
import { exitProcessIfDevMode } from "./utils/dev-mode-check";
import { syncIfKarmaFilesChange } from "./utils/karma-sync-check";

await exitProcessIfDevMode("commit");
await syncIfKarmaFilesChange();
